### ISSUE TITLE
5/28 밤샘 할일! (정민)

### ISSUE THREAD

**Issue by JjungminLee** [ODE-SEOUL/ode-seoul-frontend#53]
- [x] 케러셀 
- [x] 새로고침 issue 모두 해결 -> 시경이꺼도  (해결못함)
- [x] 프로젝트 아키텍쳐 -> 백엔드까지 포함해서 그리기 
- [x] 카테고리 초급,중급,상급 쪽 안되는거 해결
- [x] isLoading일때 스피너
- [x] 중앙 정렬
- [x] css 날라가는거
- [x] 제안서 고치기

**Comment by kweonsikyung** [comment]
하 새로고침 /{id}도 똑같네요 ㅠㅠ

**Comment by JjungminLee** [comment]
어제 고치려했는데 못고쳤어요,,, 오늘 좀만 쉬고 내일 할게여,,ㅜㅜ
